server:
  port: 8090

spring:
  application:
    name: she-culture-admin
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# 数据源配置（读取现有JSON数据）
data:
  source:
    path: classpath:db.json
